const mockData = [
    {
        id: 1,
        date: "18.10.2024",
        category: "Мусор",
        status: "active",
        deadline: "20.10.2024",
        executor: "Shavkat",
    },
    {
        id: 2,
        date: "19.10.2024",
        category: "Уборка",
        status: "completed",
        deadline: "21.10.2024",
        executor: "Olga",
    },
    {
        id: 3,
        date: "20.10.2024",
        category: "Ремонт",
        status: "active",
        deadline: "25.10.2024",
        executor: "Ivan",
    },
    {
        id: 4,
        date: "21.10.2024",
        category: "Транспортировка",
        status: "pending",
        deadline: "22.10.2024",
        executor: "Alex",
    },
    {
        id: 5,
        date: "22.10.2024",
        category: "Обслуживание",
        status: "active",
        deadline: "23.10.2024",
        executor: "Diana",
    },
    {
        id: 6,
        date: "23.10.2024",
        category: "Доставка",
        status: "completed",
        deadline: "24.10.2024",
        executor: "Sergey",
    },
    {
        id: 7,
        date: "24.10.2024",
        category: "Охрана",
        status: "active",
        deadline: "26.10.2024",
        executor: "Artem",
    },
    {
        id: 8,
        date: "25.10.2024",
        category: "Монтаж",
        status: "pending",
        deadline: "30.10.2024",
        executor: "Vladimir",
    },
    {
        id: 9,
        date: "26.10.2024",
        category: "Обследование",
        status: "completed",
        deadline: "27.10.2024",
        executor: "Natalia",
    },
    {
        id: 10,
        date: "27.10.2024",
        category: "Установка",
        status: "active",
        deadline: "29.10.2024",
        executor: "Mikhail",
    },
];

export default mockData;